# Generated by Django 5.0.2 on 2024-04-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guest', '0005_alter_booking_id_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='charges',
            field=models.FloatField(null=True),
        ),
    ]
