# Generated by Django 3.2.18 on 2024-04-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentrole', '0003_alter_maintenancerequest_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonafiedRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('id_proof', models.FileField(upload_to='')),
                ('reason', models.TextField()),
                ('approved', models.BooleanField(default=True)),
            ],
        ),
    ]
