# Generated by Django 3.2.18 on 2024-04-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentrole', '0004_bonafiedrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonafiedrequest',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
