# Generated by Django 3.2.18 on 2024-04-12 04:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(default='Mon', max_length=10)),
                ('morning_meal_name', models.CharField(default='abc', max_length=100)),
                ('dinner_meal_name', models.CharField(default='bcd', max_length=100)),
                ('description', models.CharField(default='bcd', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MessBills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('month', models.IntegerField(default=0)),
                ('bill_status_is_paid', models.BooleanField(default=False)),
                ('bill_amount', models.IntegerField(default=0)),
                ('month_name', models.CharField(default='abc', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_of_leave', models.CharField(default=None, max_length=20)),
                ('is_attending_morning', models.BooleanField(default=True)),
                ('is_attending_night', models.BooleanField(default=True)),
                ('is_penalty', models.BooleanField(default=False)),
                ('is_penalty_morning', models.BooleanField(default=False)),
                ('is_penalty_night', models.BooleanField(default=False)),
                ('month', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
