# Generated by Django 3.2.18 on 2024-04-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amenities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_time', models.DateTimeField()),
                ('booked', models.BooleanField(default=False)),
                ('patient_name', models.CharField(blank=True, max_length=100, null=True)),
                ('patient_contact', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
