# Generated by Django 3.2.18 on 2024-04-12 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Amenities', '0003_booking_slot'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='Amenities.clinicslot')),
            ],
        ),
        migrations.RemoveField(
            model_name='booking',
            name='slot',
        ),
        migrations.DeleteModel(
            name='BookingSlot',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Slot',
        ),
    ]
