# Generated by Django 3.2.18 on 2024-04-12 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amenities', '0004_auto_20240413_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
