# Generated by Django 3.2.18 on 2024-04-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amenities', '0005_slotbooking_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotbooking',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
