# Generated by Django 5.0.2 on 2024-04-13 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amenities', '0007_remove_slotbooking_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=300)),
                ('availablility', models.BooleanField()),
            ],
        ),
    ]
