# Generated by Django 3.2.18 on 2024-04-13 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Amenities', '0007_remove_slotbooking_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaundrySlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='slotbooking',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_bookings', to='Amenities.clinicslot'),
        ),
        migrations.CreateModel(
            name='LaundryBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laundry_bookings', to='Amenities.laundryslot')),
            ],
        ),
    ]
