# Generated by Django 5.0.2 on 2024-04-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amenities', '0008_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availablility',
            field=models.IntegerField(),
        ),
    ]
