# Generated by Django 5.0.2 on 2024-04-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Amenities', '0009_alter_product_availablility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availablility',
            field=models.BooleanField(),
        ),
    ]
