# Generated by Django 3.2.18 on 2024-04-13 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Amenities', '0008_auto_20240413_1505'),
        ('Amenities', '0012_remove_product_availablility_product_stock'),
    ]

    operations = [
    ]
