# Generated by Django 5.0.2 on 2024-03-05 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortlisting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='application_no',
            new_name='application_id',
        ),
    ]
