# Generated by Django 3.2.18 on 2024-04-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlisting', '0003_auto_20240325_1525'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='roommaterequest',
            name='year',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
