# Generated by Django 3.2.18 on 2024-04-08 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortlisting', '0004_auto_20240404_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='shortlisting.room')),
                ('leader', models.CharField(max_length=10)),
                ('leader_rank', models.CharField(max_length=1)),
                ('engineering_branch', models.CharField(max_length=100)),
                ('preferences', models.JSONField()),
            ],
        ),
    ]
