# Generated by Django 5.0.2 on 2024-04-08 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortlisting', '0005_room_alloted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='alloted',
        ),
    ]
