# Generated by Django 5.0.2 on 2024-04-09 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortlisting', '0006_alter_preference_leader_rank'),
        ('shortlisting', '0006_remove_room_alloted'),
    ]

    operations = [
    ]
