# Generated by Django 5.0.2 on 2024-04-11 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlisting', '0007_merge_20240409_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='alloted_room',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='alloted_room',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
