# Generated by Django 5.0.2 on 2024-03-01 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('percentile', models.FloatField()),
                ('application_id', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='hey',
        ),
    ]
