# Generated by Django 5.0.2 on 2024-03-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_studentsdata_delete_hey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('application_id', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('percentile', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'data',
            },
        ),
        migrations.DeleteModel(
            name='StudentsData',
        ),
    ]
