# Generated by Django 5.0.2 on 2024-03-02 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_remove_data_application_id_remove_data_email_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
