# Generated by Django 5.0.2 on 2024-03-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_civilengineering'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComputerEngineering',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('application_id', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('percentile', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='InstrumentationEngineering',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('application_id', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('percentile', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ManfacturingEngineering',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('application_id', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('percentile', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MechanicalEngineering',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('application_id', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('percentile', models.FloatField()),
            ],
        ),
    ]
