# Generated by Django 5.0.2 on 2024-03-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_computerengineering_instrumentationengineering_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CivilEngineering',
        ),
    ]
