# Generated by Django 3.2.9 on 2024-03-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_civilengineering'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilengineering',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='civilengineering',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computerengineering',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computerengineering',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electricalengineering',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electricalengineering',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrumentationengineering',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrumentationengineering',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manfacturingengineering',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manfacturingengineering',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mechanicalengineering',
            name='selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mechanicalengineering',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
