# Generated by Django 5.0.2 on 2024-03-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0013_civilengineering'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilengineering',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='computerengineering',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='electricalengineering',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='instrumentationengineering',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manfacturingengineering',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mechanicalengineering',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
