# Generated by Django 3.2.9 on 2024-03-05 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_auto_20240305_2210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civilengineering',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='computerengineering',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='electricalengineering',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='instrumentationengineering',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='manfacturingengineering',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='mechanicalengineering',
            name='gender',
        ),
    ]
