# Generated by Django 5.0.3 on 2024-03-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0015_auto_20240305_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password1', models.CharField(default='', max_length=70)),
                ('password2', models.CharField(default='', max_length=70)),
            ],
        ),
    ]
