# Generated by Django 5.0.2 on 2024-03-12 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0014_civilengineering_verification_status_and_more'),
        ('registration', '0015_auto_20240305_2213'),
    ]

    operations = [
    ]
