# Generated by Django 5.0.3 on 2024-03-15 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('reson', models.CharField(max_length=100)),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
