# Generated by Django 5.0.3 on 2024-03-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0017_checkinout_delete_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinout',
            name='mis',
            field=models.IntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkinout',
            name='year',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='check_in_time',
            field=models.DateTimeField(verbose_name='timezone.now'),
        ),
    ]
