# Generated by Django 5.0.3 on 2024-03-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_checkinout_mis_checkinout_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkinout',
            old_name='reson',
            new_name='reason',
        ),
    ]
