# Generated by Django 5.0.3 on 2024-03-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0020_alter_checkinout_check_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
