# Generated by Django 3.2.18 on 2024-03-25 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0018_auto_20240323_1759'),
        ('registration', '0022_alter_checkinout_check_out_time'),
    ]

    operations = [
    ]
