# Generated by Django 3.2.18 on 2024-03-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0023_merge_20240325_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout',
            name='mis',
            field=models.IntegerField(),
        ),
    ]
