# Generated by Django 5.0.2 on 2024-04-01 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0025_firstyear'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirstYear',
        ),
    ]
