# Generated by Django 3.2.18 on 2024-04-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0027_auto_20240404_0653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerengineering',
            name='user',
        ),
        migrations.RemoveField(
            model_name='electricalengineering',
            name='user',
        ),
        migrations.RemoveField(
            model_name='instrumentationengineering',
            name='user',
        ),
        migrations.RemoveField(
            model_name='manfacturingengineering',
            name='user',
        ),
        migrations.RemoveField(
            model_name='mechanicalengineering',
            name='user',
        ),
        migrations.DeleteModel(
            name='CivilEngineering',
        ),
        migrations.DeleteModel(
            name='ComputerEngineering',
        ),
        migrations.DeleteModel(
            name='ElectricalEngineering',
        ),
        migrations.DeleteModel(
            name='InstrumentationEngineering',
        ),
        migrations.DeleteModel(
            name='ManfacturingEngineering',
        ),
        migrations.DeleteModel(
            name='MechanicalEngineering',
        ),
    ]
