# Generated by Django 5.0.2 on 2024-04-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0028_auto_20240404_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalyear',
            name='alloted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firstyear',
            name='alloted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secondyear',
            name='alloted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thirdyear',
            name='alloted',
            field=models.BooleanField(default=False),
        ),
    ]
