# Generated by Django 5.0.2 on 2024-04-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0030_remove_finalyear_alloted_remove_firstyear_alloted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_period', models.CharField(max_length=100)),
                ('selected_students_list', models.DateField()),
                ('preference_selection_date', models.CharField(max_length=100)),
                ('final_room_allotment', models.DateField()),
            ],
        ),
    ]
