# Generated by Django 5.0.2 on 2024-04-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0031_selecteddates'),
    ]

    operations = [
        migrations.AddField(
            model_name='selecteddates',
            name='verification_period',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
