# Generated by Django 3.2.18 on 2024-04-12 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0033_delete_checkinout'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalyear',
            name='caste',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='finalyear',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='firstyear',
            name='caste',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='firstyear',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='secondyear',
            name='caste',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='secondyear',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thirdyear',
            name='caste',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='thirdyear',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
