# Generated by Django 5.0.2 on 2024-04-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_delete_third_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Third_Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mis_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('verified', models.BooleanField(default=False)),
                ('selected', models.BooleanField(default=False)),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
    ]
