# Generated by Django 3.2.18 on 2024-04-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0034_auto_20240412_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='finalyear',
            old_name='rank',
            new_name='cgpa',
        ),
        migrations.RenameField(
            model_name='firstyear',
            old_name='rank',
            new_name='cgpa',
        ),
        migrations.RenameField(
            model_name='secondyear',
            old_name='rank',
            new_name='cgpa',
        ),
        migrations.RenameField(
            model_name='thirdyear',
            old_name='rank',
            new_name='cgpa',
        ),
    ]
