# Generated by Django 5.0.2 on 2024-04-03 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0035_third_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Third_Year',
        ),
    ]
