# Generated by Django 5.0.2 on 2024-04-03 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0040_fourth_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fourth_Year',
        ),
    ]
