# Generated by Django 3.2.18 on 2024-03-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlisting', '0003_auto_20240323_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student1', models.CharField(max_length=10)),
                ('student2', models.CharField(max_length=10)),
                ('student3', models.CharField(max_length=10)),
                ('student4', models.CharField(max_length=10)),
            ],
        ),
    ]
