# Generated by Django 3.2.18 on 2024-03-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlisting', '0004_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='student1',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='student2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='student3',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='student4',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
