# Generated by Django 3.2.18 on 2024-03-25 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortlisting', '0004_alter_application_id'),
        ('shortlisting', '0005_auto_20240324_1114'),
    ]

    operations = [
    ]
