# Generated by Django 5.0.2 on 2024-04-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminrole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('message', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
